C MEMBER XOBP51
C DESC PRINTS GENERATED TIME SERIES
C
C@PROCESS LVL(77)
C
      SUBROUTINE XOBP51(WK,LAOBS)
C---------------------------------------------------------------------
C  ROUTINE TO PRINT GENERATE POOL ELEVATIONS (AND STORAGES) AND
C  DISCHARGES. INPUT FOR THE PROCEDURE CAN BE EITHER AN OBSERVED
C  ELEVATION TS OR OBSERVED DISCHARGE TS OR BOTH. DIFFERENT STRATEGIES
C  ARE USED FOR THE DIFFERENT COMBINATIONS OF TIME SERIES AND THEIR
C  TIME INTERVALS.
C---------------------------------------------------------------------
C  WRITTEN BY KUANG HSU - HRL - OCTOBER 1994
C---------------------------------------------------------------------
C
C  LAOBS -- LAST PERIOD WITH NON-MISSING OBSERVED DATA WITHIN NRUN
C  TIME SERIES SEQUENCE STORED IN PO ARRAY --
C     (QI1),QI2,QO1,QO2,(QOM),(POOL),(STORAGE),(OBSQO),(OBSQOM),(OBSH),
C              (QO1,QO2,(QOM),(POOL),(STORAGE),(OBSQO),(OBSQOM),(OBSH))
C
 
      COMMON/FCTIME/IDARUN,IHRRUN,LDARUN,LHRRUN,LDACPD,LHRCPD,NOW(5),
     .  LOCAL,NOUTZ,NOUTDS,NLSTZ,IDA,IHR,LDA,LHR,IDADAT
C LC commented out FPROG common block; not used
C      COMMON/FPROG/MAINUM,VERS,VDATE(2),PNAME(5),NDD
      COMMON/IONUM/IN,IPR,IPU
      COMMON/SARR51/IDOFST,MINODT,
     & IRES,NRES,NRUN,NS2,NTIM24,NUM,ITME(1)
      COMMON/LTS51/
     & LPQI1,LPQI2,LPQO1,LPQO2,LPQM,LPEL,LPST,LPOQO,LPOQM,LPOEL,
     &  LPQL1,LPQL2,LPBQI1,LPBQI2,LPBQIM,
     & LIQI1,LIQI2,LIQO1,LIQO2,LIQM,LIEL,LIST,LIOQO,LIOQM,LIOEL,
     &  LIQL1,LIQL2,LIBQI1,LIBQI2,LIBQIM,
     & LDQI1,LDQI2,LDQO1,LDQO2,LDQM,LDEL,LDST,LDOQO,LDOQM,LDOEL,
     &  LDQL1,LDQL2,LDBQI1,LDBQI2,LDBQIM,
     & LWQO1,LWQO2,LWQM,LWEL,LWST,LWBQI1,LWBQI2,LWBQIM
      INCLUDE 'flogm'
C
      DIMENSION WK(*)
C
C    ================================= RCS keyword statements ==========
      CHARACTER*68     RCSKW1,RCSKW2
      DATA             RCSKW1,RCSKW2 /                                 '
     .$Source: /fs/hseb/ob72/rfc/ofs/src/fcst_ssarresv/RCS/xobp51.f,v $
     . $',                                                             '
     .$Id: xobp51.f,v 1.1 1996/03/21 13:46:49 page Exp $
     . $' /
C    ===================================================================
C
C
      IF (FEWSDEBUG.LT.2) GO TO 9000
C
C  WRITE INST. GEN. DISCHARGES
C
      WRITE(MESSAGESTRING,1690)
      call logfromfortran(DEBUG_LEVEL,MESSAGESTRING)
 1690 FORMAT(/10X,'** INST. GEN. DISCHARGES AT PERIOD START **')
      WRITE(MESSAGESTRING,1651) (WK(LWQO1+I-1),I=1,LAOBS)
      call logfromfortran(DEBUG_LEVEL,MESSAGESTRING)
C
      WRITE(MESSAGESTRING,1691)
      call logfromfortran(DEBUG_LEVEL,MESSAGESTRING)
 1691 FORMAT(/10X,'** INST. GEN. DISCHARGES AT PERIOD END **')
      WRITE(MESSAGESTRING,1651) (WK(LWQO2+I-1),I=1,LAOBS)
      call logfromfortran(DEBUG_LEVEL,MESSAGESTRING)
C
C  WRITE MEAN GEN. DISCHARGES
C
      WRITE(MESSAGESTRING,1692)
      call logfromfortran(DEBUG_LEVEL,MESSAGESTRING)
 1692 FORMAT(/10X,'** MEAN GEN. DISCHARGES **')
      WRITE(MESSAGESTRING,1651) (WK(LWQM+I-1),I=1,LAOBS)
      call logfromfortran(DEBUG_LEVEL,MESSAGESTRING)
C
C  WRITE GEN. POOL ELEVATIONS
C
      WRITE(MESSAGESTRING,1694)
      call logfromfortran(DEBUG_LEVEL,MESSAGESTRING)
 1694 FORMAT(/10X,'** GEN. POOL ELEVATIONS **')
      WRITE(MESSAGESTRING,1652) (WK(LWEL+I-1),I=1,LAOBS)
      call logfromfortran(DEBUG_LEVEL,MESSAGESTRING)
C
C  WRITE GEN. STORAGES
C
      WRITE(MESSAGESTRING,1696)
      call logfromfortran(DEBUG_LEVEL,MESSAGESTRING)
 1696 FORMAT(/10X,'** GEN. STORAGES **')
      WRITE(MESSAGESTRING,1650) (WK(LWST+I-1),I=1,LAOBS)
      call logfromfortran(DEBUG_LEVEL,MESSAGESTRING)
C
 9000 CONTINUE
      
 1650 FORMAT(5X,8F10.0)
      
 1651 FORMAT(5X,8F10.1)
      
 1652 FORMAT(5X,8F10.2)
C
      RETURN
      END
