#!/usr/bin/ksh
usage="USAGE: runall\n"

for segdef in almn8  cyfm4     ltkw3     oolo2x    swrn6grl  towv1uct \
              crvi4  giln6hud  mmdn6grl  sacn6hud  synres    wymm1me; 
do
inputDir=$PWD/testData/$segdef
progname=${PWD##*/}
echo -e "\n\n ===> $progname <==="
echo -e "\n Basin Name: " $segdef
dirname=bin

if [[ $segdef == "towv1uct" || $segdef == "giln6hud" || $segdef == "mmdn6grl" || 
   $segdef == "wymm1me" || $segdef == "sacn6hud" || $segdef == "swrn6grl" ]]
then
   dtstr="3\n39541\n24\n39542\n6\n39550\n24"
elif [[ $segdef == "almn8" || $segdef == "crvi4" || $segdef == "ltkw3" || 
   $segdef == "synres" || $segdef == "cyfm4" ]]
then
    dtstr="3\n39642\n24\n39643\n6\n39666\n24"
elif [[ $segdef == "oolo2x" ]] 
then
   dtstr="1\n39556\n24\n39557\n6\n39565\n24"
fi

#define NWS data type and dataunit files
NWSDATATYPEFILE=../nwsrfs_datatype_mapping_file.txt
NWSDATAUNITFILE=../nwsrfs_dataunit_file.txt

#rm old files produced by model
rm -rf $inputDir/diag.txt $inputDir/statesI.txt

$dirname/$progname $inputDir/params.txt \
                   $inputDir/statesI.txt $inputDir/diag.txt \
                   $NWSDATATYPEFILE $NWSDATAUNITFILE > log.txt

#valgrind --track-origins=yes --tool=memcheck --leak-check=full --show-reachable=yes $dirname/$progname $inputDir/params.txt $inputDir/statesI.txt $inputDir/diag.txt $NWSDATATYPEFILE $NWSDATAUNITFILE

echo
diff $inputDir/statesI.txt $inputDir/statesI.txt.orig
if [[ $? == 0 ]]
then
   echo -e " No StatesO diffs found.\n"
fi
echo -e '=================> End ' $segdef ' <================='
done
