      SUBROUTINE SNDEPTH(WE,SLIQ,SFALL,SMELT,SGMLOS,SRFRZ,
     +                   TA,DTA,IDT,SNDPT,SNDEN,SNTMP)
C
C....................................................................
C
C  SUBROUTINE CALCULATES SNOW DEPTH AND SNOW TEMPERATURE FOR THE 
C    COMPUTATIONAL TIME PERIOD
C
C     INITIALLY WRITTEN BY VICTOR KOREN IN APRIL 2000.
C
C     MODIFIED 11/05 BY E. ANDERSON
C       - VARIABLE NAMES CHANGED TO BE CONSISTENT FROM ONE ROUTINE TO
C         THE NEXT.
C       - SIGNIFICANT CHANGES TO COMPUTATIONAL SEQUENCE
C
C....................................................................
C
      COMMON/FDBUG/IODBUG,ITRACE,IDBALL,NDEBUG,IDEBUG(20)
C
C    ================================= RCS keyword statements ==========
CGW      CHARACTER*68     RCSKW1,RCSKW2
CGW      DATA             RCSKW1,RCSKW2 /                                 '
CGW     .$Source: /fs/hseb/ob90/ohd/ofs/src/fcst_snow/RCS/sndepth19.f,v $
CGW     . $',                                                             '
CGW     .$Id: sndepth19.f,v 1.2 2006/10/03 19:32:54 hsu Exp $
CGW     . $' /
C    ===================================================================
C
C     INPUT VARIABLES
C **  WE     - WATER EQUIVALENT, MM
C **  SLIQ   - LIQUID WATER CONTENT, MM
C **  SFALL  - NEW SNOWFALL, MM
C **  SMELT  - SURFACE MELT, MM
C **  SGMLOS - GROUND MELT, MM
C **  SRFRZ  - REFROZEN MELT/RAIN WATER, MM
C **  TA     - AIR TEMPERATURE, C
C **  DTA    - AIR TEMPERATURE CHANGE FROM THE PREVIOUS TIME PERIOD  
C **  IDT    - TIME STEP OF THE COMPUTATIONAL PERIOD, HR
C **  SNDPT  - SNOW DEPTH, CM
C **  SNDEN  - SNOW DENSITY, G/CM3 (ICE PORTION OF SNOW COVER)
C **  SNTMP  - AVERAGE SNOW TEMPERATURE, C
C **  IBUG   - DEBUG FLAG
C
C     OTHER VARIABLES
C **  TSNEW  - TEMP OF NEW SNOW, C
C **  DPTNEW - DEPTH OF NEW SNOW, CM
C **  DENNEW - DENSITY OF NEW SNOW, G/CM3
C **  DCM    - DENSITY INCREASE DUE TO MELT METAPHORISM
C                (REFREEZING OF LIQUID WATER), MULTIPLYING FACTOR
C **  WE1    - VALUE OF WE AT THE START OF THE PERIOD, MM
C **  WEX    - WATER EQUIVALENT OF EXISTING SNOW AT END OF PERIOD, MM
C **  DPTOLD - DEPTH OF OLD SNOW AFTER ANY MELT, CM
C **  TSNDPT - TOTAL DEPTH (OLD AND NEW SNOW), CM
C **  TSNDEN - TOTAL DENSITY (OLD AND NEW SNOW), G/CM3
C **  SFALLX - SNOWFALL MINUS MELT, MM
C **  PLOSS  - TOTAL MELT DURING THE PERIOD - SURFACE MELT PLUS
C                GROUNDMELT, MM
C
C  VALUES INPUT TO THE SUBROUTINE
C    WE, SLIQ - VALUE AT THE END OF THE CURRENT COMPUTATIONAL 
C       TIME PERIOD
C    SFALL, SMELT, SGMLOS, SRFRZ - AMOUNTS THAT OCCUR DURING THE PERIOD
C    TA - PERIOD AVERAGE VALUE
C    SNDPT, SNDEN, SNTMP - VALUE AT THE BEGINNING OF THE PERIOD
C  VALUES OUTPUT
C    SNDPT, SNDEN, SNTMP - VALUE AT THE END OF THE PERIOD
C
C  CHECK FOR DEBUG
CGW      IF (IBUG.GT.0) WRITE(IODBUG,900) SNDPT,SNDEN,SNTMP,TA,DTA,
CGW     1  WE,SLIQ,SFALL,SMELT,SGMLOS,SRFRZ
CGW  900 FORMAT(1H ,2X,23HSNDEPTH19 INPUT--SNDPT=,F7.2,7H SNDEN=,F6.3,
CGW     1  7H SNTMP=,F6.2,4H TA=,F6.2,5H DTA=,F6.2,4H WE=,F8.2,
CGW     2  6H SLIQ=,F6.2,/10X,7H SFALL=,F7.3,7H SMELT=,F7.3,
CGW     3  8H SGMLOS=,F7.3,7H SRFRZ=,F7.3)
      DT=IDT
C    ASSUME TEMPERATURE OF ANY NEW SNOW = AVG. AIR TEMPERATURE
C      AS FAR AS COMPUTING THE DENSITY OF NEW SNOW - ACTUAL
C      TEMPERATURE OF NEW SNOW CANNOT EXCEED 0.0 DEGC.
      DPTNEW=0.0
      DENNEW=0.0
      TSNEW=TA
      IF (SNDPT.GT.0.0) GO TO 100
C********************************************************************
C********************************************************************
C    NEW SNOW COVER - NONE EXISTED AT START OF PERIOD
C      KNOWN - WE.GT.0.0 (IF NOT, ROUTINE WOULDN'T BE CALLED)
C            - SFALL.GT.0 (SINCE SNOW EXISTS AND THERE WAS NONE
C                AT THE START OF THE PERIOD)
C     COMPUTE NET SNOWFALL DURING THE PERIOD
C        - SNOWFALL MINUS ANY SURFACE AND GROUND MELT.
C        - NET SNOWFALL POSITIVE OR NO SNOW WOULD EXIST
      SFALLX=SFALL-SMELT-SGMLOS
C     COMPUTE DEPTH AND DENSITY OF NET SNOWFALL
      CALL SNEW(TSNEW,SFALLX,DPTNEW,DENNEW)
C     ACCOUNT FOR ANY REFREEZE - INCREASES DENSITY - RECOMPUTE DEPTH
      IF (SRFRZ.GT.0.0) THEN
        DCM=(SFALLX+SRFRZ)/SFALLX
        DENNEW=DCM*DENNEW
        DPTNEW=(0.1*WE)/DENNEW
      ENDIF
C     SET TOTAL SNOW COVER VALUES AT END OF PERIOD.
      SNDPT=DPTNEW
      SNDEN=DENNEW
      SNTMP=TSNEW
      IF (SNTMP.GT.0.0) SNTMP=0.0
C   CHECK FOR DEBUG
CGW      IF (IBUG.GT.0) WRITE(IODBUG,901) SFALLX,SNDPT,SNDEN,SNTMP
CGW  901 FORMAT(1H ,2X,29HNEW SNOW ONLY OUTPUT--SFALLX=,F7.3,
CGW     1  7H SNDPT=,F7.2,7H SNDEN=,F5.3,7H SNTMP=,F6.2)
      RETURN
C********************************************************************
C********************************************************************
C    SNOW COVER EXISTED AT START OF PERIOD
C     COMPUTE CHANGE IN DENSITY AND DEPTH OF EXISTING COVER
C     INCORPORATE EFFECT OF ANY NEW SNOW DURING THE PERIOD
C
C     COMPUTE NET MELT DURING PERIOD
  100 PLOSS=SMELT+SGMLOS
C     COMPUTE WE VALUE AT THE START OF THE PERIOD - EXISTING SNOW
      WE1=WE-SFALL+PLOSS-SRFRZ
C     CHECK FOR VARIOUS CASES
      IF (PLOSS.LT.WE1) THEN
C...............................................................
C     AMOUNT OF MELT IS LESS THAN EXISTING SNOW AT START OF PERIOD
C       ASSUME ALL MELT CAME FROM EXISTING SNOW - TYPICAL CASE
C     CHECK FOR ANY NEW SNOWFALL DURING PERIOD
C       IF ANY, GET DEPTH AND DENSITY
        IF (SFALL.GT.0.0) CALL SNEW(TSNEW,SFALL,DPTNEW,DENNEW)
C     COMPUTE WATER EQUIVALENT OF EXISTING SNOW AT END OF PERIOD
C       - PRIOR TO ANY REFREEZE
        WEX=WE1-PLOSS
C     COMPUTE DEPTH OF REMAINING OLD SNOW - ASSUME DENSITY OF
C       MELTED SNOW WAS THE SAME AS THE AVERAGE DENSITY OF THE
C       TOTAL OLD SNOW COVER
        DPTOLD=(0.1*WEX)/SNDEN
C     USE DENSITY OF COMBINED OLD AND NEW SNOW TO COMPUTE THE
C       THERMAL CONDUCTIVITY TO USE FOR CALCULATING THE CHANGE
C       IN THE TEMPERATURE OF THE SNOW COVER.
        TSNDPT=DPTOLD+DPTNEW
        TSNDEN=(DPTOLD*SNDEN+DPTNEW*DENNEW)/TSNDPT
C     COMPUTE NEW TEMPERATURE OF THE OLD SNOW
        CALL SNOWT(TSNDPT,TSNDEN,WE,SLIQ,TA,DTA,SNTMP,DPTNEW,IDT)
C     COMPUTE NEW DEPTH AND DENSITY OF OLD SNOW AFTER EFFECT OF
C       COMPACTION AND DESTRUCTIVE METAMORPHISM ARE TAKEN INTO
C       ACCOUNT.
        CALL SNOWPACK(WEX,DT,SNDPT,SNDEN,SLIQ,SNTMP)
C     CHECK FOR DEBUG
CGW        IF (IBUG.GT.0) WRITE(IODBUG,902) SNDPT,SNDEN,DPTNEW,DENNEW,
CGW     1    SNTMP,TSNEW
CGW  902   FORMAT(1H ,2X,26HMELT FROM OLD SNOW--SNDPT=,F7.2,7H SNDEN=,
CGW     1    F5.3,8H DPTNEW=,F6.2,8H DENNEW=,F5.3,7H SNTMP=,F6.2,
CGW     2    7H TSNEW=,F6.2)
      ELSE
        SFALLX=SFALL-PLOSS
        IF (SFALLX.GT.0.0) THEN
C...............................................................
C       MELT DURING THE PERIOD WAS GREATER THAN THE AMOUNT OF SNOW
C         AT THE START OF THE PERIOD AND NEW SNOWFALL EXCEEDS THE
C         AMOUNT OF MELT DURING THE PERIOD - ASSUME MELT COMES FROM
C         NEW SNOWFALL
C         GET DEPTH AND DENSITY OF NEW SNOW
          CALL SNEW(TSNEW,SFALLX,DPTNEW,DENNEW)
C         USE DENSITY OF COMBINED OLD AND NEW SNOW TO COMPUTE THE
C           THERMAL CONDUCTIVITY TO USE FOR CALCULATING THE CHANGE
C           IN THE TEMPERATURE OF THE SNOW COVER.
          TSNDPT=SNDPT+DPTNEW
          TSNDEN=(SNDPT*SNDEN+DPTNEW*DENNEW)/TSNDPT
C         COMPUTE NEW TEMPERATURE OF THE OLD SNOW
          CALL SNOWT(TSNDPT,TSNDEN,WE,SLIQ,TA,DTA,SNTMP,DPTNEW,IDT)
C         COMPUTE NEW DEPTH AND DENSITY OF OLD SNOW AFTER EFFECT OF
C           COMPACTION AND DESTRUCTIVE METAMORPHISM ARE TAKEN INTO
C           ACCOUNT.
          CALL SNOWPACK(WE1,DT,SNDPT,SNDEN,SLIQ,SNTMP)
C         CHECK FOR DEBUG
CGW          IF (IBUG.GT.0) WRITE(IODBUG,903) SNDPT,SNDEN,DPTNEW,DENNEW,
CGW     1    SNTMP,TSNEW
CGW  903   FORMAT(1H ,2X,26HMELT FROM NEW SNOW--SNDPT=,F7.2,7H SNDEN=,
CGW     1    F5.3,8H DPTNEW=,F6.2,8H DENNEW=,F5.3,7H SNTMP=,F6.2,
CGW     2    7H TSNEW=,F6.2)
        ELSE
C...............................................................
C       SFALLX IS .LE. 0.0, THUS MELT EXCEEDS BOTH EXISTING SNOW
C         AT THE START OF THE PERIOD AND THE NEW SNOWFALL, BUT NOT
C         THE TOTAL OF THE TWO QUANTITIES.  ASSUME ALL NEW SNOW
C         MELTS AND ONLY PART OF THE EXISTING PACK REMAINS.
          WEX=WE-SRFRZ
C         DEPTH OF EXISTING SNOW THAT REMAINS
          TSNDPT=(0.1*WEX)/SNDEN
C         COMPUTE NEW TEMPERATURE OF THE REMAINING OLD SNOW
          CALL SNOWT(TSNDPT,SNDEN,WE,SLIQ,TA,DTA,SNTMP,DPTNEW,IDT)
C         COMPUTE NEW DEPTH AND DENSITY OF REMAINING OLD SNOW AFTER
C           EFFECT OF COMPACTION AND DESTRUCTIVE METAMORPHISM ARE
C           TAKEN INTO ACCOUNT.
          CALL SNOWPACK(WEX,DT,SNDPT,SNDEN,SLIQ,SNTMP)
C         CHECK FOR DEBUG
CGW          IF (IBUG.GT.0) WRITE(IODBUG,904) SNDPT,SNDEN,DPTNEW,DENNEW,
CGW     1    SNTMP,TSNEW
CGW  904   FORMAT(1H ,2X,26HALL NEW SNOW MELTS--SNDPT=,F7.2,7H SNDEN=,
CGW     1    F5.3,8H DPTNEW=,F6.2,8H DENNEW=,F5.3,7H SNTMP=,F6.2,
CGW     2    7H TSNEW=,F6.2)
        ENDIF
      ENDIF
C...............................................................
C     IN ALL CASES WHEN SNOW EXISTED AT THE START OF THE PERIOD
C       COMPUTE NEW TOTAL DEPTH AND TEMPERATURE BY WEIGHING BOTH
C       THE OLD AND NEW SNOW.
      IF (TSNEW.GT.0.0) TSNEW=0.0
      SNTMP=(SNTMP*SNDPT+TSNEW*DPTNEW)/(SNDPT+DPTNEW)
      SNDPT=SNDPT+DPTNEW
      SNDEN=(0.1*(WE-SRFRZ))/SNDPT
C     COMPUTE EFFECT OF MELT METAMORPHISM - REFREEZING OF LIQUID
C       WATER WITHIN THE SNOW COVER.
      IF (SRFRZ.EQ.0.0) GO TO 110
C     COMPUTE INCREASE IN DENSITY DUE TO REFREEZING
      DCM=WE/(WE-SRFRZ)
      SNDEN=SNDEN*DCM
C     CHECK THAT DENSITY IS WITHIN THE RANGE OF 0.05 TO 0.60
  110 IF (SNDEN.GT.0.6) SNDEN=0.6
      IF (SNDEN.LT.0.05) SNDEN=0.05
C     COMPUTE SNOW DEPTH AT THE END OF THE PERIOD
      SNDPT=(0.1*WE)/SNDEN
C     CHECK FOR DEBUG
CGW      IF (IBUG.GT.0) WRITE(IODBUG,905) SNDPT,SNDEN,SNTMP
CGW  905 FORMAT(1H ,2X,24HSNDEPTH19 OUTPUT--SNDPT=,F7.2,7H SNDEN=,F5.3,
CGW     1  7H SNTMP=,F6.2)
C
C***************************************************************
CEA  PREVIOUS VERSION OF THE SUBROUTINE FOLLOWS:
CEA      SUBROUTINE SNDEPTH19(WE,SLIQ,SFALL,SGSLOS,SRFRZ,
CEA     +                   TA,DTA,IDT,SNDPT,SNDEN,SNTMP)
C **  WE     - WATER EQUIVALENT, MM
C **  SLIQ   - LIQUID WATER CONTENT, MM
C **  DFALL  - NEW SNOWFALL, MM
C **  SGSLOS - GROUND SNOW MELT, MM
C **  SRFRZ  - REFROZEN MELT/RAIN WATER, MM
C **  TA     - AIR TEMPERATURE, C
C **  DTA    - AIR TEMPERATURE CHANGE FOR THE 6HR TIME INTERVAL  
C **  IDT    - TIME STEP, HR
C **  SH     - SNOW DEPTH, CM
C **  DS     - SNOW DENSITY, G/CM3
C **  TSNOW  - AVERAGE SNOW TEMPERATURE, CELSIUS
CEA      DT=IDT
C  ADJUST SNOW DENSITY DUE TO SNOWFALL
CEA      DHC=0.
CEA      SDN=0.0
CEA      TSNEW=TA
CEA      IF(DFALL .GT. 0.) THEN
C  CALCILATE NEW SNOW FALL DEPTH/DENSITY
CEA       CALL SNEW(TA,DFALL,DHC,SDN)
CEA       CALL SNOWT(DHC,SDN,DFALL,0.,TA,DTA,TSNEW,0.)
CEA       CALL SNOWPACK(DFALL,DT,DHC,SDN,0.,0.,0.,TSNEW)
CEA      ENDIF
CEA      IF(SH .GT. 0.0001) THEN
C  CALCULATE OLD SNOW COMPACTION/METAMORPHISM
CEA       SHN=DHC+SH
CEA       DSN=(SDN*DHC+DS*SH)/SHN
CEA       CALL SNOWT(SHN,DSN,WE,SLIQ,TA,DTA,TSNOW,DHC)
CEA       CALL SNOWPACK(WE,DT,SH,DS,SLIQ,DFALL,SRFRZ,TSNOW)
C  ACCOUNT FOR GROUND SNOW MELT
CEA       IF(SGSLOS .GT. 0.) SH=SH-0.1*SGSLOS/DS
CEA       IF(SH .LT. 0.) SH=0.0
C  COMBINE NEW SNOW FALL AND OLD SNOWPACK
CEA       TSNOW=(TSNOW*SH+TSNEW*DHC)/(SH+DHC)
CEA       SH=SH+DHC
CEA       DS=0.1*WE/SH
CEA      ELSE
C  THERE WAS NO SNOWPACK BEFORE THIS SNOW FALL
CEA       SH=DHC
CEA       DS=SDN
CEA       IF(SGSLOS .GT. 0.) SH=SH-0.1*SGSLOS/DS
CEA       IF(SH .LT. 0.) SH=0.0
CEA       TSNOW=TSNEW
CEA      ENDIF
C***************************************************************
      RETURN
      END
