      SUBROUTINE SNOWT(SNDPT,SNDEN,WE,SLIQ,TA,DTA,SNTMP,DPTNEW,IDT)
C
C  SUBROUTINE CALCULATES AVERAGE SNOW TEMPERATURE
C      SNDPT   - SNOW DEPTH, CM (OLD AND NEW SNOW AFTER MELT)
C      SNDEN   - SNOW DENSITY, G/CM3 (OLD AND NEW SNOW AFTER MELT)
C      WE      - SNOW WATER EQUIVALENT, MM
C      SLIG    - TOTAL LIQUID WATER IN THE SNOW COVER, MM
C      TA      - AVERAGE AIR TEMPERATURE FOR THE CURRENT PERIOD, C
C      DTA     - CHANGE IN AIR TEMPERATURE FROM THE PREVIOUS PERIOD, C
C      SNTMP   - SNOW TEMPERATURE, C
C         INPUT - AT BEGINNING OF PERIOD (EXISTING SNOW)
C         OUTPUT - AT END OF PERIOD (OLD SNOW ONLY)
C      DPTNEW  - DEPTH OF NET NEW SNOWFALL DURING THE PERIOD, CM
C      IDT     - COMPUTATIONAL TIME INTERVAL, HR
C
C  SPECIFIC HEAT CAPACITIES OF ICE, WATER, AND AIR
C    UNITS ARE WATTS SEC/(M**3 C)
      PARAMETER (CICE=2.1E06,CH2O=4.2E06,CAIR=1E03)
C  HEAT WAVE LENGTH, IN SECONDS
      WAVEL=2.0*3600.*IDT      
C
C    CONVERT DEPTHS TO METERS
       SNDPTM=0.01*SNDPT
       DPTNWM=0.01*DPTNEW
C    GET TOTAL WATER EQUIVALENT AND DENSITY (SOLID PLUS LIQUID WATER)
       WETOT=WE+SLIQ
       DENTOT=0.1*WETOT/SNDPT 
C    COMPUTE THERMAL CONDUCTIVITY
       TC=0.0442*EXP(5.181*DENTOT)
C    COMPUTE FRACTION LIQUID
       FL=SLIQ/WETOT
C    COMPUTE EFFECTIVE SPECIFIC VOLUMETRIC HEAT CAPACITY
       C=CICE*SNDEN+CAIR*(1.-SNDEN-FL)+CH2O*FL
C    COMPUTE NEW SNOW COVER TEMPERATURE
       ALP=SQRT(3.14*C/(WAVEL*TC))
       IF(DPTNEW .GT. 0.) THEN
        SNTMP=SNTMP+DTA*((EXP(-ALP*DPTNWM)-EXP(-ALP*SNDPTM))/
     +        (ALP*(SNDPTM-DPTNWM)))
       ELSE
        SNTMP=SNTMP+DTA*((1.-EXP(-ALP*SNDPTM))/(ALP*SNDPTM))
       ENDIF 
      IF(SNTMP .GT. 0.) SNTMP=0.
      RETURN
      END