      SUBROUTINE SNOWPACK (WE,DT,SNDPT,SNDEN,SLIQ,SNTMP)
C
C ****************************************************************
C **  SUBROUTINE CALCULATES SNOW COMPACTION AND DESTRUCTIVE    ***
C **  METAMORPHISM - ALSO COMPONENT OF MELT METAMORPHISM DUE   ***
C **  TO THE PRESENCE OF LIQUID WATER IS ACCOUNTED FOR.        ***
C **  EQUATIONS FOR INCREASING SNOW DENSITY WERE OBTAINED AS   ***
C **  APPROXIMATE SOLUTIONS OF E. ANDERSON DIFFERENTIAL        ***
C **  EQUATIONS (3.29) AND (3.30), (3.31), NOAA TECHNICAL      *** 
C **  REPORT NWS 19, by   VICTOR KOREN   03/25/95              ***
C **                                                           ***
C **  MODIFIED 11/05 BY E. ANDERSON -                          ***
C **    SOME VARIABLE NAMES CHANGED TO PROVIDE CONSISTENCY     ***
C **    EFFECT OF SNOWFALL, MELT, AND REFREEZE ON DEPTH NOW    ***
C **    MOVED UP TO CALLING ROUTINE - SNDEPTH19                ***
C ****************************************************************
C
C ***************************************************************
C  WE     - WATER EQUIVALENT OF THE ICE PORTION OF THE        ***
C            REMAINING PART OF THE SNOW COVER THAT EXISTED    ***
C            AT THE START OF THE COMPUTATIONAL PERIOD, MM     ***
C  DT     - LENGTH OF COMPUTATIONAL TIME PERIOD, HRS          ***
C  SNDPT  - SNOW DEPTH, CM                                    ***
C  SNDEN  - SNOW DENSITY, G/CM3                               ***
C  SLIQ   - LIQUID WATER CONTENTS, MM (END OF PERIOD)         ***
C  SNTMP  - AVERAGE SNOW TEMPERATURE OF REMAINING EXISTING    ***
C             SNOW COVER, C (END OF PERIOD)                   ***
C                                                             ***
C   INPUT -SNDPT AND SNDEN AT BEGINNING OF PERIOD             ***
C   OUTPUT - SNDPT AND SNDEN - VALUES FOR REMAINING EXISTING  ***
C     SNOW AFTER COMPACTION AND DESTRUCTIVE METAMORPHISM      ***
C ***************************************************************
C
      REAL*8 B
      COMMON/FDBUG/IODBUG,ITRACE,IDBALL,NDEBUG,IDEBUG(20)
C
C  CONSTANTS OF SNOW COMPACTION AND DESTRUCTIVE METAMORPHISM
C    MODELS FROM ANDERSON - TECHNICAL REPORT 19:
C    C1 IN 1/(CM HR), C2 IN CM3/G, C3 IN 1/HR, C4 IN 1/DEGREE C,
C    C5 DIMENSIONLESS, THRESD IN G/CM3, CX IN CM3/G
C    ONLY PARAMETER C5 WAS CHANGED FROM 0.15 TO 0.20 BASED ON
C    RESULTS OF SIMULATIONS USING NOAA-ARS COOPERATIVE SNOW 
C    RESEARCH PROJECT DATA 
CEA  BASED ON COMPARISON AT ALL SNOWMIP LOCATIONS AND SEVERAL
CEA    OTHER SITES THE SNOW METAMORPHISM PARAMETERS WERE FURTHER
CEA    MODIFIED TO PRODUCE IMPROVED RESULTS OVER A WIDER RANGE OF
CEA    CLIMATOLOGICAL CONDITIONS.
      PARAMETER (C1=0.026, C2=21.0)
      PARAMETER (C3=0.005, C4=0.10, THRESD=0.15, C5=2.,CX=23.)
C
C **  CONVERT WATER EQUIVALENT TO CENTIMETERS
      SNDPT1=SNDPT
      SNDEN1=SNDEN
      WECM=WE*0.1
C
C **  CALCULATE CHANGE IN DENSITY AS A RESULT OF COMPACTION
C **  C1 IS THE FRACTIONAL INCREASE IN DENSITY (1/(CM*HR)) 
C **  C2 IS A CONSTANT (CM3/G) Kojima estimated as 21 cms/g
C   
      DCC=1.
      IF(WECM.GT.1E-2) THEN
        B=DT*C1*EXP(0.08*SNTMP-C2*SNDEN)
        DCC=(DEXP(B*WECM)-1.)/(B*WECM)
      ENDIF
C
C **  CALCULATE THE DENSITY CHANGE AS A RESULT OF DESTRUCTIVE
C       METAMORPHISM AND COMPONENT OF MELT METAPHORISM DUE TO
C       THE PRESENCE OF LIQUID WATER
C     C3 IS THE FRACTIONAL SETTLING RATE AT 0 DEGREE FOR DENSITIES 
C        LESS THAN THRESHOLD DENSITY, THRESD
C     C4 IS A CONSTANT 
C     C5 IS AN EMPIRICAL ADJUSTMENT FACTOR THAT ACCOUNTS FOR
C        THE PRESENCE OF LIQUID WATER
C 
      A1=C3
      IF(SLIQ .GT. 0.) A1=A1*C5
      A2=C4*SNTMP
      IF(SNDEN.GT.THRESD) A2=A2-CX*(SNDEN-THRESD)
      A=A1*DT*EXP(A2)
      DCD=EXP(A)

C **  NEW SNOW DENSITY OF EXISTING SNOW AS A RESULT OF COMPACTION
C **   AND DESTRUCTIVE METAMORPHISM 
      SNDEN=SNDEN*DCC*DCD
C **  NEW DEPTH OF EXISTING SNOW AFTER DENSITY CHANGE
      SNDPT=WECM/SNDEN
CGW      IF (IBUG.EQ.1) WRITE(IODBUG,900) WE,SNDPT1,SNDEN1,SNTMP,SLIQ,
CGW     1  SNDPT,SNDEN,DCC,DCD
CGW  900 FORMAT(1H ,2X,20HSNOWPACK INPUT - WE=,F8.2,7H SNDPT=,F7.2,
CGW     1  7H SNDEN=,F5.3,7H SNTMP=,F5.1,6H SLIQ=,F5.2,/7X,
CGW     2  15HOUTPUT - SNDPT=,F7.2,7H SNDEN=,F5.3,5H DCC=,F7.5,
CGW     3  5H DCD=,F7.5)
C********************************************************************
CEA  PREVIOUS VERSION OF THE ROUTINE AS FOLLOWS
CEA      SUBROUTINE SNOWPACK ( W,DTS,HC,DS,SLIQ,DFALL,SRFRZ,TSNOW)
C
C **************************************************************
C  W      IS A WATER EQUIVALENT OF SNOW, IN MM               ***
C  DTS    IS A TIME STEP, IN HOURS                           ***
C  HC     IS A SNOW DEPTH, IN CM                              ***
C  DS     IS A SNOW DENSITY, IN G/CM3                        ***
C  SLIQ   IS A LIQUID WATER CONTENTS, MM                     ***
C  TSNOW  IS AN AVERAGE SNOW TEMPERATURE, CELSIUS            ***
C      SUBROUTINE WILL RETURN NEW VALUES OF H AND DS         ***
C **************************************************************
C
CEA      REAL*8 B
C
C  CONSTANTS OF SNOW COMPACTION/METAMORPHISM MODELS. FROM ANDERSON
C  TECHNICAL REPORT 19:
C    C1 IN 1/(CM HR), C2 IN CM3/G, C3 IN 1/HR, C4 IN 1/DEGREE C,
C    C5 DIMENSIONLESS, RDS IN G/CM3, CX IN CM3/G
C    ONLY PARAMETER C5 WAS CHANGED FROM 0.15 TO 0.20 BASED ON
C    RESULTS OF SIMULATIONS USING NOAA-ARS COOPERATIVE SNOW 
C    RESEARCH PROJECT DATA 
CEA      PARAMETER (C1=0.01, C2=21.0)
CEA      PARAMETER (C3=0.01, C4=0.04, RDS=0.20, C5=2.,CX=46.)
C
C **  CONVERSION INTO SIMULATION UNITS
CEA      WX=W*0.1
C
C **  CALCULATING OF SNOW DEPTH AND DENSITY AS A RESULT OF COMPACTION
C **  C1 IS THE FRACTIONAL INCREASE IN DENSITY (1/(CM*HR)) 
C **  C2 IS A CONSTANT (CM3/G) Kojima estimated as 21 cms/g
C   
CEA     DSC=1.
CEA     IF(WX.GT.1E-2) THEN
CEA        B=DTS*C1*EXP(0.08*TSNOW-C2*DS)
CEA        DSC=(DEXP(B*WX)-1.)/(B*WX)
CEA      ENDIF
C
C **  CALCULATE THE DENSITY CHANGE AS A RESULT OF SNOW METAMORPHISM
C     C3 IS THE FRACTIONAL SETTLING RATE AT 0 DEGREE FOR DENSITIES 
C        LESS THAN THRESHOLD DENSITY, RDS
C     C4 IS A CONSTANT 
C     C5 IS AN EMPIRICAL ADJUSTMENT FACTOR THAT ACCOUNTS FOR MELT
C        METAMORPHISM
C 
CEA      A=C3
CEA      IF(SLIQ .GT. 0.) A=A*C5
CEA      C=C4*TSNOW
CEA      IF(DS .GT. RDS) C=C-CX*(DS-RDS)
CEA      DSM=EXP(A*DTS*EXP(C))
C **  NEW SNOW DENSITY AS A RESULT OF COMPACTION-METAMORPHISM 
CEA      DSX=DS*DSC*DSM
CEA      IF(DSX .GT. 0.45) DSX=0.45
CEA      IF(DSX .LT. 0.05) DSX=DS
CEA      DS=DSX
CEA      DWX=WX-0.1*(DFALL+SRFRZ)
CEA      IF(DWX .GT. 0.) THEN
CEA       HC=DWX/DS
CEA      ELSE 
CEA       IF(WX .GT. 0.) THEN
CEA        HC=WX/DSX
CEA       ELSE
CEA        HC=0.0
CEA       ENDIF  
CEA      ENDIF
C********************************************************************
      RETURN
      END

