PGM = genStatesResj

RESJ_DIR = ../../resj
RESJ_OBJ = ${RESJ_DIR}/src/resjchps/resj_writeStates.o

OTHERINCLUDE = -I${RESJ_DIR}/include
OTHERLIB = ${RESJ_DIR}/lib/libresj.a
BUILD = objs
SUBDIRS = genStatesResj 

#include ../Makefile4TopgenStates
include ../Makefile4Top
