C  CALL SUBROUTINE FST2SAC1 TO GET SAC-SMA MOISTURE STATES 
C
cv07      SUBROUTINE FRZ2SAC1(PX,ZSOIL,SMC,SH2O,NUPL,NSAC,SWLT,RTUZ,RTLZ,
      SUBROUTINE FRZ2SAC1(PX,ZSOIL,NUPL,NSAC,SWLT,RTUZ,RTLZ,iexit)
CP 03/09     +    iout,iexit)
      
cv07      REAL ZSOIL(*),SMC(*),SH2O(*)
      REAL ZSOIL(*)
      REAL LZTWC,LZFSC,LZFPC,LZTWH,LZFSH,LZFPH

cc      COMMON/IONUM/IN,IPR,IPU      

      COMMON/FSMCO1/UZTWC,UZFWC,LZTWC,LZFSC,LZFPC,ADIMC,FGCO(6),RSUM(7),
     1           PPE,PSC,PTA,PWE,PSH,TSOIL(8),smc(8),sh2o(8)
cv07     +               ppx,ppsc,pta,pwe,psh,tsoil(8)     
cc      COMMON/FRZCNST/ FRST_FACT,CKSOIL,ZBOT
      COMMON/FRZCNST/ FRST_FACT,ZBOT      
           
C  GET UPPER ZONE STATES
      UZTWH=FGCO(2)
      UZFWH=FGCO(3)
      XH=0.
      XC=0.

      CALL FST2SAC1(ZSOIL,SMC,SH2O,2,NUPL,SWLT,RTUZ,UZTWH,UZFWH,XH,
     +              UZTWC,UZFWC,XC,FROST1,PX,iexit)
CP 03/09 +              UZTWC,UZFWC,XC,FROST1,PX,iout,iexit)

      if(FROST1 .eq. 0.) then
       FGCO(1)=0.
      else
       FGCO(1)=-FROST1/FRST_FACT
      endif 
      FGCO(2)=UZTWH
      FGCO(3)=UZFWH

C  GET LOWER ZONE STATES
      LZTWH=FGCO(4)
      LZFSH=FGCO(5)
      LZFPH=FGCO(6)
      NUP=NUPL+1

      CALL FST2SAC1(ZSOIL,SMC,SH2O,NUP,NSAC,SWLT,RTLZ,LZTWH,LZFSH,
     +              LZFPH,LZTWC,LZFSC,LZFPC,FROST2,0.,iexit)
CP 03/09 +          LZFPH,LZTWC,LZFSC,LZFPC,FROST2,0.,iout,iexit)
      if(FROST2 .ne. 0.) FGCO(1)=FGCO(1)-FROST2/FRST_FACT
cc      FGCO(1)=FGCO(1)-FROST2/FRST_FACT
      FGCO(4)=LZTWH
      FGCO(5)=LZFSH
      FGCO(6)=LZFPH

      RETURN
      END
