C MODULE MAEICQ
C-----------------------------------------------------------------------
C
C
C
C     DESC - THIS SUBROUTINE PERFORMS THE AEICQN MOD
C
C
C
      SUBROUTINE MAEICQ(IIDATE, NVALUES, VALUES, IVOP, IHZERO, MODTZC)
C
C
      INCLUDE 'flogm'
      INCLUDE 'fctime'
C      
      COMMON/MOD135/NDT35,IDT35(5),VAL35(5)
C
      CHARACTER MODNAM*6, MODTZC*4 
      DIMENSION VALUES(NVALUES) 
      INTEGER   NVALUES, IIDATE(NVALUES) 
      DATA MODNAM/'AEICQN'/
C
      IF (FEWSDEBUG.GT.1) THEN
        WRITE(MESSAGESTRING,*) '*** AEICQN MOD ENTERED' 
        call logfromfortran(DEBUG_LEVEL, MESSAGESTRING)
      END IF
C
C     CHECK IF API-CONT OPERATION USES THE AEI OPTION.
C   
      IF (IVOP.NE.1) GO TO 380
C
      NDT35 = 1
20    IDATE=IIDATE(NDT35)
      IF(MOD(IDATE,24).EQ.0)GO TO 50
C
C  SKIP MOD IF DATE ENTERED IS NOT AT THE END OF A HYDROLOGIC DAY
C
      IXDA=IDATE/24+1
      IXHR=IDATE-(IXDA-1)*24
      CALL MDYH2(IXDA,IXHR,IM1,ID1,IY1,IH1,DUM1,DUM2,MODTZC)
C
      WRITE(MESSAGESTRING,30)IM1,ID1,IY1,IH1,MODTZC
      call logfromfortran(WARNING_LEVEL, MESSAGESTRING)
30    FORMAT(1H0,10X,'**WARNING** THE DATE FOR CHANGES IN THE ',
     1 'AEICQN MOD (',I2,1H/,I2,1H/,I4,1H-,I2,1X,A4,1H)/11X,
     2 'IS NOT AT THE END OF A HYDROLOGIC DAY.'/11X,
     3 'THE DATE FOR THIS CHANGE WILL BE MOVED TO THE END OF ',
     4 'THE HYDROLOGIC DAY.')
      IDATE=(IDATE/24)*24 + 24
C
C     SEE IF DATE IS WITHIN RUN PERIOD
C
50    CONTINUE
      ICOMP=((LDACPD-1)*24)+LHRCPD
      IF (IDATE.LE.ICOMP) GOTO 60
      GOTO 380
C
60    ISTHR=(IDA-1)*24+IHZERO
      IENHR=(LDA-1)*24+LHR
C
      IF(ISTHR.LT.IDATE.AND.IENHR.GE.IDATE)GO TO 90
C
C     DATE FOR CHANGES NOT IN ALLOWABLE WINDOW
C
      CALL MDYH2(IDA,IHZERO,IM1,ID1,IY1,IH1,DUM1,DUM2,MODTZC)
      CALL MDYH2(LDA,LHR,IM2,ID2,IY2,IH2,DUM1,DUM2,MODTZC)
      IXDA=IDATE/24+1
      IXHR=IDATE-(IXDA-1)*24
      IF(IXHR.EQ.0)IXDA=IXDA-1
      IF(IXHR.EQ.0)IXHR=24
      CALL MDYH2(IXDA,IXHR,IM3,ID3,IY3,IH3,DUM1,DUM2,MODTZC)
C
      IF(ISTHR.NE.IDATE) THEN
        WRITE(MESSAGESTRING,70)IM3,ID3,IY3,IH3,MODTZC,IM1,ID1,IY1,IH1,
     1  MODTZC, IM2,ID2,IY2,IH2,MODTZC
        call logfromfortran(WARNING_LEVEL, MESSAGESTRING)
70      FORMAT(1H0,10X,'**WARNING** THE DATE FOR CHANGES IN THE ',
     1 'AEICQN MOD (',I2,1H/,I2,1H/,I4,1H-,I2,1X,A4,1H)/11X,
     2 'IS NOT IN THE CURRENT RUN PERIOD (',I2,1H/,I2,
     3 1H/,I4,1H-,I2,1X,A4,4H TO ,I2,1H/,I2,1H/,I4,1H-,I2,1X,A4,1H)/
     4 11X,'THESE CHANGES WILL BE IGNORED.')
      END IF
      
      IF(ISTHR.EQ.IDATE) THEN
        WRITE(MESSAGESTRING,80)IM3,ID3,IY3,IH3,MODTZC
        call logfromfortran(WARNING_LEVEL, MESSAGESTRING)
80      FORMAT(1H0,10X,'**WARNING** THE DATE FOR CHANGES IN THE ',
     1 'AEICQN MOD (',I2,1H/,I2,1H/,I4,1H-,I2,1X,A4,1H)/11X,
     2 'IS AT THE START OF THE CURRENT RUN PERIOD.'/
     3 11X,'THESE CHANGES WILL BE IGNORED.')
      END IF
      GO TO 380
C
90    CONTINUE 
C
C     STORE VALUE IN COMMON BLOCK /MOD135/
C
C  ***** NOTE THAT THE DATE IS STORED IN IDT35 AS JULIAN DAYS *****
C
      IDT35(NDT35)=IIDATE(NDT35)/24+1
      VAL35(NDT35)=VALUES(NDT35)
      IF (NVALUES.GT.5.OR.NDT35.GE.NVALUES)  GO TO 330
      NDT35 = NDT35 + 1
      GO TO 20
C
330   CONTINUE
C
      WRITE(MESSAGESTRING,350)(IIDATE(I),VALUES(I),I=1,NVALUES)
      call logfromfortran(DEBUG_LEVEL, MESSAGESTRING)
350   FORMAT(11X,'IN SUBROUTINE MAEICQ - AEICQN MOD'/11X,
     1 'IDATE, VALUE = ',I11,1X,G9.2)
C
      IF(NDT35.GT.0) THEN
        WRITE(MESSAGESTRING,360)(IDT35(I),VAL35(I),I=1,NDT35)
        call logfromfortran(DEBUG_LEVEL, MESSAGESTRING)
360     FORMAT(1HO,10X,'APPLY AEICQN MOD - IDT35 (julian days), VAL35 ='
     ./(20X,2G9.2))
      END IF
C
380   IF(FEWSDEBUG.GT.1) THEN
        WRITE(MESSAGESTRING,*) '==> LEAVING SUBROUTINE MAEICQ'
        call logfromfortran(DEBUG_LEVEL, MESSAGESTRING)
      END IF
      
      RETURN
      END
