C  MODULE MAIADJ
C
C  DESC - PERFORMS THE AIADJ MOD
C
      SUBROUTINE MAIADJ(VALUE,IDATE,PVALUE,IHZERO,MODTZC)

      INCLUDE 'flogm'
      INCLUDE 'fctime'
C
      IF(FEWSDEBUG.GT.1) THEN
         WRITE(MESSAGESTRING,900) IDATE
         call logfromfortran(DEBUG_LEVEL, MESSAGESTRING)
  900    FORMAT(' *** AIADJ MOD ENTERED, IDATE=',I11)
      END IF
C
C  SEE IF DATE IS WITHIN RUN PERIOD
C
      ISTHR=(IDA-1)*24+IHZERO
      IENHR=(LDA-1)*24+LHR
C
      IF(ISTHR.LE.IDATE.AND.IENHR.GE.IDATE)GO TO 11
C
C  DATE NOT WITHIN ALLOWABLE WINDOW
C
      CALL MDYH2(IDA,IHZERO,IM1,ID1,IY1,IH1,DUM1,DUM2,MODTZC)
      CALL MDYH2(LDA,LHR,IM2,ID2,IY2,IH2,DUM1,DUM2,MODTZC)
      IXDA=IDATE/24+1
      IXHR=IDATE-(IXDA-1)*24
      IF(IXHR.EQ.0)IXDA=IXDA-1
      IF(IXHR.EQ.0)IXHR=24
      CALL MDYH2(IXDA,IXHR,IM3,ID3,IY3,IH3,DUM1,DUM2,MODTZC)
C
      WRITE(MESSAGESTRING,602)IM3,ID3,IY3,IH3,MODTZC,IM1,ID1,IY1,IH1,
     1MODTZC,IM2,ID2,IY2,IH2,MODTZC
      call logfromfortran(WARNING_LEVEL, MESSAGESTRING)
  602 FORMAT(1H0,10X,'**WARNING** THE DATE FOR CHANGES ENTERED IN THE ',
     1 'AIADJ MOD (',I2,1H/,I2,1H/,I4,1H-,I2,1X,A4,1H)/11X,
     2 'IS NOT WITHIN THE CURRENT RUN PERIOD (',I2,1H/,I2,
     3 1H/,I4,1H-,I2,1X,A4,4H TO ,I2,1H/,I2,1H/,I4,1H-,I2,1X,A4,1H)/
     4 11X,'THESE CHANGES WILL BE IGNORED.')
C
      GO TO 999
C
   11 CONTINUE
C
      IF(VALUE.GE.-5.0.AND.VALUE.LE.5.0)GO TO 115
C
C  BAD AI VALUE ENTERED
C
      WRITE(MESSAGESTRING,604) 'API-CONT', VALUE
      call logfromfortran(WARNING_LEVEL,MESSAGESTRING)
  604 FORMAT(1H0,10X,'**WARNING** IN AIADJ MOD - VALUE IS OUT OF ',
     1 'VALID RANGE FOR ',A8,' OPERATION '/11X,'VALUE ENTERED AS ',
     2 G10.4)
C
      IF(VALUE.GT.5.0)VALUE=5.0
      IF(VALUE.LT.-5.0)VALUE=-5.0
C
      WRITE(MESSAGESTRING,607) VALUE
      call logfromfortran(WARNING_LEVEL,MESSAGESTRING)
  607 FORMAT(11X,'VALUE RESET TO ',F4.1)
C
  115 CONTINUE
C
C     NO CONVERSION FOR API-CONT
C
      PVALUE=VALUE
      
      WRITE(MESSAGESTRING,902)PVALUE,24,'API-CONT'
      call logfromfortran(DEBUG_LEVEL,MESSAGESTRING)
  902 FORMAT(1H0,10X,'APPLY AIADJ MOD - '/11X,
     1 'A VALUE OF ',F8.2,' HAS BEEN STORED IN THE P ARRAY OF ',
     2 'OPERATION ',I2,' NAMED ',A8,' AS THE AI ADJUSTMENT.')
C
  999 IF(FEWSDEBUG.GT.1) THEN
        WRITE(MESSAGESTRING,*) '==> LEAVING SUBROUTINE MAIADJ'
        call logfromfortran(DEBUG_LEVEL, MESSAGESTRING)
      END IF

      RETURN
      END
