C MODULE MAPICB
C-----------------------------------------------------------------------
C
C
C     DESC - PERFORMS THE APICBASF MOD
C
      SUBROUTINE MAPICB(IIDATE, NUMVALS, VALUES, IHZERO, MODTZC)
C
      INCLUDE 'flogm'
      INCLUDE 'fctime'
C      
      COMMON/FAPICO/NAPICS,APICOS(12,10)
C   
      CHARACTER*8 OPNAME
      INTEGER IIDATE(NUMVALS), NUMVALS
      REAL    VALUES(NUMVALS)
C
C
      IF(FEWSDEBUG.GT.1) THEN
        WRITE(MESSAGESTRING,*) '*** APICBASF MOD ENTERED'
        call logfromfortran(DEBUG_LEVEL,MESSAGESTRING)
      END IF
C
      NVAL=1
      
 50   IDATE = IIDATE(NVAL)

      ICOMP=((LDACPD-1)*24)+LHRCPD
      IF (IDATE.LE.ICOMP) GOTO 20
      GOTO 250
C
C     SEE IF DATE IS WITHIN RUN PERIOD, PLUS OR MINUS 12 HOURS
C
20    CONTINUE
      ISTHR=(IDA-1)*24+IHZERO
      IENHR=(LDA-1)*24+LHR
C
      IF(ISTHR-12.LE.IDATE.AND.IENHR+12.GE.IDATE)GO TO 40
C
C     DATE NOT WITHIN ALLOWABLE WINDOW
C
      CALL MDYH2(IDA,IHZERO,IM1,ID1,IY1,IH1,DUM1,DUM2,MODTZC)
      CALL MDYH2(LDA,LHR,IM2,ID2,IY2,IH2,DUM1,DUM2,MODTZC)
      IXDA=IDATE/24+1
      IXHR=IDATE-(IXDA-1)*24
      IF(IXHR.EQ.0)IXDA=IXDA-1
      IF(IXHR.EQ.0)IXHR=24
      CALL MDYH2(IXDA,IXHR,IM3,ID3,IY3,IH3,DUM1,DUM2,MODTZC)
C
      WRITE(MESSAGESTRING,30)IM3,ID3,IY3,IH3,MODTZC,IM1,ID1,IY1,IH1,
     1MODTZC,IM2,ID2,IY2,IH2,MODTZC
      call logfromfortran(WARNING_LEVEL,MESSAGESTRING)
30    FORMAT(1H0,10X,'**WARNING** THE DATE FOR CHANGES ENTERED IN THE ',
     1 'APICBASF MOD (',I2,1H/,I2,1H/,I4,1H-,I2,1X,A4,1H)/11X,
     2 'IS NOT WITHIN THE CURRENT RUN PERIOD (',I2,1H/,I2,
     3 1H/,I4,1H-,I2,1X,A4,4H TO ,I2,1H/,I2,1H/,I4,1H-,I2,1X,A4,1H)/
     4 11X,'THESE CHANGES WILL BE IGNORED.')
      GO TO 250
C
 40   IF (NUMVALS.LE.0 .OR. NUMVALS.GT.10) GO TO 250
      OPNAME='API-CONT'
C
      IF(VALUES(NVAL).GE.0.)GO TO 140
C
C     BAD BASEFLOW ADJUSTMENT VALUE ENTERED
C
c     IF(MODWRN.EQ.1)
      WRITE(MESSAGESTRING,130) VALUES(NVAL)
      call logfromfortran(WARNING_LEVEL,MESSAGESTRING)
130   FORMAT(1H0,10X,'**WARNING** IN APICBASF MOD - VALUE IS OUT OF ',
     1 'VALID RANGE '/11X,'VALUE = ',G10.4)
C
      IF ( NVAL .GE. NUMVALS ) GO TO 250
      NVAL = NVAL + 1
      GO TO 50 
C
140   CONTINUE
C
C     SEE IF ANY SETS OF CARRYOVER IN CB /FAPICO/
C
      IF(NAPICS.GT.0)GO TO 200
C
C     NONE IN CB - JUST ADD THIS CARRYOVER TO CB
C
      NAPICS=1
      CALL UMEMOV(OPNAME,APICOS(1,1),2)
      APICOS(3,1)=IDATE+0.01
      CALL UMEMST(-999.,APICOS(4,1),9)
      APICOS(11,1)=VALUES(NVAL)
C
      IF ( NVAL .GE. NUMVALS ) GO TO 250
      NVAL = NVAL + 1
      GO TO 50
C
200   CONTINUE
C
C     SEE IF OPER NAME AND DATE MATCHES ANY VALUES CURRENTLY IN CB
C
      DO 210 I=1,NAPICS
      IF(IUSAME(OPNAME,APICOS(1,I),2).EQ.0)GO TO 210
C
C     NAME MATCHES - NOW CHECK DATE
C
      IF(IFIX(APICOS(3,I)).NE.IDATE)GO TO 210
C
C     DATES MATCH TOO - CHANGE VALUE IN CB
C
      APICOS(11,I)=VALUES(NVAL)
      GO TO 240
C
210   CONTINUE
C
C     NO MATCH FOR OPER NAME AND DATE - ADD TO CB IF THERE IS ROOM
C
      IF(NAPICS.LT.10)GO TO 230
C
C     NOT ENOUGH ROOM
C
      WRITE(MESSAGESTRING,220)
      call logfromfortran(WARNING_LEVEL,MESSAGESTRING)
220   FORMAT(1H0,10X,'**WARNING** NOT ENOUGH ROOM IN COMMON BLOCK ',
     1 '/FAPICO/'/11X,'TO HOLD A NEW BASEFLOW MULTIPLIER.')
C
      GO TO 240
C
C     ENOUGH ROOM - ADD
C
230   NAPICS=NAPICS+1
      CALL UMEMOV(OPNAME,APICOS(1,NAPICS),2)
      APICOS(3,NAPICS)=IDATE+0.01
      CALL UMEMST(-999.,APICOS(4,NAPICS),9)
      APICOS(11,NAPICS)=VALUES(NVAL)
C
240   CONTINUE 
      IF ( NVAL .GE. NUMVALS ) GO TO 250
      NVAL = NVAL + 1
C      NVAL = NAVAL + 1  --- this line has typo error, fixed as above line by RHC for FogBugz 614 at Nov. 2012
      GO TO 50
C
250   IF ( NAPICS.GT.0 ) THEN
         WRITE(MESSAGESTRING,190) NAPICS,((APICOS(J,I),J=1,12),
     1                            I=1,NAPICS)
         call logfromfortran(DEBUG_LEVEL,MESSAGESTRING)
190      FORMAT(1H0,10X,'APPLY APICBASF MOD - NAPICS=',I5/
     1 (11X,'APICOS=',1X,2A4,F8.0,9F8.2))
      END IF
C
      IF(FEWSDEBUG.GT.1) THEN
        WRITE(MESSAGESTRING,*) '==> LEAVING SUBROUTINE MAPICB'
        call logfromfortran(DEBUG_LEVEL,MESSAGESTRING)
      END IF
C
      RETURN
      END
