CVK  FROZEN GROUND VERSION, IVERS, IS ADDED:
CVK    IVERS=1, ERIC'S VERSION
CVK         =2, VK_FROST ONLY VERSION
CVK         =3, VK_ALL VERSION
C12/02VK    =4, NO FREEZING WATER VERSION
CVK  NSL IS A MAXIMUM NUMBER OF SOIL LAYERS; =8   

      SUBROUTINE FSTFG1(FGCO,TSOIL,FGPM,state,IVERS,smc,sh2o)
      
      REAL FGCO(*),TSOIL(*),FGPM(*),state(6),smc(*),sh2o(*)
      COMMON/FRDSTFG/SMAX,PSISAT,BRT,SWLT,QUARTZ,STYPE,NUPL,
     +               NSAC,RTUP,RTLW,DZUP,DZLOW
cc      COMMON/FRZCNST/ FRST_FACT,CKSOIL,ZBOT
      COMMON/FRZCNST/ FRST_FACT,ZBOT      
      IF(IVERS .GT. 1) THEN
CVK  ESTIMATE INITIAL SAC-SMA UNFROZEN WATER STORAGES
CVK  IF THEY ARE NOT INPUTED
        CALL ESTFST1(FGCO,TSOIL,FGPM,state,smc,sh2o)

CVK  CHECKING CONSISTENCY OF UNFROZEN WATER STATES
       L=0
       SFI=0.
       DO I=1,5
        IF(FGCO(I+1) .EQ. -999. .OR. FGCO(I+1) .GT. state(I)) THEN 
         FGCO(I+1)=state(I)
         L=1
        ENDIF 
        SFI=SFI+state(I)-FGCO(I+1)
       ENDDO
       xx1=ABS(FGCO(1)*FRST_FACT)
       xx2=1.1*SFI       
       IF(xx1 .GT. xx2) THEN
        FGCO(1)=-SFI/FRST_FACT
        L=1
       ENDIF 
       xx1=ABS(FGCO(1)*FRST_FACT)
       xx2=0.9*SFI
       IF(xx1 .LT. xx2) THEN
        FGCO(1)=-SFI/FRST_FACT
        L=1
       ENDIF
     
       IF (L.NE.0) THEN
        WRITE (IPR,920) IVERS
  920 FORMAT (1H0,25X,25H**WARNING FROM VERSION **,I3)
        WRITE (IPR,921)
  921 FORMAT (1H ,10X,43HINITIAL STATE VARIABLES CONTAIN IMPOSSIBLE ,
     1 7HVALUES.,5X,5HUZTWH,2X,5HUZFWH,2X,5HLZTWH,2X,5HLZFSH,2X,5HLZFPH,
     2 2X,5HFINDX)
        WRITE (IPR,922) (FGCO(I),I=2,6),FGCO(1)
  922 FORMAT (1H ,50X,10HCHANGED TO,3X,6F7.0)
       ENDIF

      ENDIF  
      
      RETURN
      END
