      FUNCTION SURFRZ1(FROST,CVFRZ,CRFRZ)

C    ESTIMATION OF IMPERMEABLE AREA FRACTION DUE TO FROZEN GROUND
C    FROST - FROST INDEX=SICE/(-5.). THIS WAS DONE TO BE 
C            CONSISTENT WITH ERIC'S FROST INDEX.
C    CVFRZ - ICE CONTENT DISTRIBUTION PARAMETER = 1/Cv**2, (Cv is SPATIAL 
C            COEFFICIENT VARIATION OF ICE CONTENT)
C    CRFRZ - ICE CONTENT VALUE ABOVE WHICH FROZEN GROUND BECOME
C            PRACTICALLY IMPERMEABLE

cc      COMMON/FRZCNST/ FRST_FACT,CKSOIL,ZBOT
      COMMON/FRZCNST/ FRST_FACT,ZBOT      
            
      SURFRZ1 = 0.
      IF(CVFRZ .EQ. 0.) GOTO 7
      SICE=-FRST_FACT * FROST 
cc      IF ( SICE .GT. CRFRZ) THEN
cc       sice=sice-crfrz 
      IF ( SICE .GT. 1.E-2) THEN 
        ACRT = CVFRZ * CRFRZ / SICE 
        IALP1 = CVFRZ + 0.5 
        SUM = EXP(-ACRT)
        K=1
        DO J = IALP1,2,-1
         IPOW=IALP1-J+1
         K = K * IPOW
         X=-ACRT+IPOW*LOG(ACRT)-LOG(FLOAT(K))
         SUM=SUM+EXP(X)
CC         SUM = SUM + (ACRT ** IPOW) / FLOAT (K) 
        ENDDO 
        SURFRZ1 = SUM 
      ENDIF
7     RETURN
      END 
