C MODULE MAPICC
C-----------------------------------------------------------------------
C
C
C     DESC - PERFORMS THE APICCO MOD
C
      SUBROUTINE MAPICC(IIDATE, NUMVALS, PVALUE, IFIELD, IHZERO, MODTZC)
C
      COMMON/FAPICO/NAPICS,APICOS(12,10)
C
      INCLUDE 'fctime'
      INCLUDE 'flogm'
C
      CHARACTER*8 OPNAME,KWRDS
      INTEGER NUMVALS
      INTEGER IIDATE(NUMVALS), IFIELD(7)
      DIMENSION VALUES(7), PVALUE(NUMVALS), KWRDS(7)
C
      DATA KWRDS /'API     ','SMI     ','SMID    ','BFSC    ',
     1 'BFI     ','FI      ','FEI     '/
C
      IF (FEWSDEBUG.GE.1) THEN         
         WRITE(MESSAGESTRING,10) NAPICS
         call logfromfortran(DEBUG_LEVEL, MESSAGESTRING)
 10      FORMAT(/' *** APICCO MOD ENTERED - NAPICS=',I5)
C
         IF (NAPICS.GT.0) THEN
           WRITE(MESSAGESTRING,440)((APICOS(J,K),J=1,12),K=1,NAPICS)
           call logfromfortran(DEBUG_LEVEL, MESSAGESTRING)
         END IF
C
      END IF
C!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      NVAL = 1
 70   IDATE = IIDATE(NVAL)
      IKEY = IFIELD(NVAL)
C
      ICOMP=((LDACPD-1)*24)+LHRCPD
      IF (IDATE.LE.ICOMP) GOTO 40
      GOTO 420
C
C     SEE IF DATE IS WITHIN - OR + 12 HOURS OF START OR END OF RUN
C
40    CONTINUE
      ISTHR=(IDA-1)*24+IHZERO
      IENHR=(LDA-1)*24+LHR
C
      IF (ISTHR-12.LE.IDATE.AND.IENHR+12.GE.IDATE) GO TO 60
C
C     DATE NOT WITHIN ALLOWABLE WINDOW
C
      CALL MDYH2(IDA,IHZERO,IM1,ID1,IY1,IH1,DUM1,DUM2,MODTZC)
      CALL MDYH2(LDA,LHR,IM2,ID2,IY2,IH2,DUM1,DUM2,MODTZC)
      IXDA=IDATE/24+1
      IXHR=IDATE-(IXDA-1)*24
      IF (IXHR.EQ.0) IXDA=IXDA-1
      IF (IXHR.EQ.0) IXHR=24
      CALL MDYH2(IXDA,IXHR,IM3,ID3,IY3,IH3,DUM1,DUM2,MODTZC)
C
      WRITE(MESSAGESTRING,50) IM3,ID3,IY3,IH3,MODTZC,IM1,ID1,IY1,IH1,
     1MODTZC,IM2,ID2,IY2,IH2,MODTZC
      call logfromfortran(WARNING_LEVEL, MESSAGESTRING)
50    FORMAT(1H0,10X,'**WARNING** THE DATE FOR CHANGES ENTERED IN THE ',
     1 'APICCO MOD (',I2,1H/,I2,1H/,I4,1H-,I2,1X,A4,1H)/11X,
     2 'IS NOT WITHIN 12 HOURS OF THE CURRENT RUN PERIOD (',I2,1H/,I2,
     3 1H/,I4,1H-,I2,1X,A4,4H TO ,I2,1H/,I2,1H/,I4,1H-,I2,1X,A4,1H)/
     4 11X,'THESE CHANGES WILL BE IGNORED.')
      GO TO 420
C
60    CONTINUE
C
      OPNAME='API-CONT'
C
       DO 110 I=1,7
 110   VALUES(I)=-9999.
C
      VALUES(IKEY)=PVALUE(NVAL)
C
C     SEE IF ANY SETS OF CARRYOVER IN CB /FAPICO/
C
 220   IF (NAPICS.GT.0) GO TO 310
C
C     NONE IN CB - JUST ADD THIS CARRYOVER TO CB
C
      NAPICS=1
      CALL UMEMOV(OPNAME,APICOS(1,1),2)
      APICOS(3,1)=IDATE+0.01
      DO 230 I=4,12
 230  APICOS(I,1)=-999.
 
      DO 300 I=1,7
      VALUE=VALUES(I)
      IF(VALUE.LT.-9998.) GO TO 300
      IF(I.LT.6.AND.VALUE.GE.0.) GO TO 290
      IF(I.EQ.6.AND.VALUE.GE.-450..AND.VALUE.LE.32.) GO TO 290
      IF(I.EQ.7.AND.VALUE.GE.0.0.AND.VALUE.LE.1.0) GO TO 290
C
C     INVALID RANGE FOR VALUE
C
      WRITE(MESSAGESTRING,250) KWRDS(I)
      call logfromfortran(WARNING_LEVEL,MESSAGESTRING)
 250  FORMAT(1H0,10X,'**WARNING** IN APICCO MOD - VALUE IS OUT OF ',
     1 'VALID RANGE FOR VARIABLE ',A8)
C
      IF(I.LT.6) THEN
        WRITE(MESSAGESTRING,260) VALUE
        call logfromfortran(WARNING_LEVEL,MESSAGESTRING)
 260    FORMAT(11X,'VALUE IS ',G10.3,' IN.')
      END IF
C
      IF(I.EQ.6) THEN
        WRITE(MESSAGESTRING,270) VALUE
        call logfromfortran(WARNING_LEVEL,MESSAGESTRING)
 270    FORMAT(11X,'VALUE IS ',G10.3,' DEGF.')
      END IF
C      
      IF(I.EQ.7) THEN
        WRITE(MESSAGESTRING,280) VALUE
        call logfromfortran(WARNING_LEVEL,MESSAGESTRING)
 280    FORMAT(11X,'VALUE IS ',G10.3)
      END IF
C     
      GO TO 300
C
 290  APICOS(I+3,1)=VALUE
 300  CONTINUE
C
      IF ( NVAL .GE. NUMVALS ) GO TO 420
      NVAL = NVAL + 1
      GO TO 70  
C
310   CONTINUE
C
C     CHECK IF NAME MATCHES ANY NAME IN CB OR IS BLANK -
C       AND IF DATE MATCHES ANY DATE IN CB
C
      DO 350 I=1,NAPICS
      IF(IUSAME(OPNAME,APICOS(1,I),2).EQ.0)GO TO 350
C
C     NAME IN CB MATCHES NAME TO BE STORED
C     NOW SEE IF DATES MATCH
C
      IDTCHK=APICOS(3,I)
      IF(IDTCHK.NE.IDATE)GO TO 350
C
C     DATES MATCH TOO - ADD INFO TO THIS SPOT IN CB
C
      DO 340 J=1,7
      VALUE=VALUES(J)
      IF(VALUE.LT.-9998.) GO TO 340
      IF(J.LT.6.AND.VALUE.GE.0.) GO TO 330
      IF(J.EQ.6.AND.VALUE.GE.-450..AND.VALUE.LE.32.) GO TO 330
      IF(J.EQ.7.AND.VALUE.GE.0.0.AND.VALUE.LE.1.0) GO TO 330
C
C     INVALID RANGE FOR VALUE
C
      WRITE(MESSAGESTRING,250) KWRDS(J)
      call logfromfortran(WARNING_LEVEL,MESSAGESTRING)
C
      IF(J.LT.6) THEN
        WRITE(MESSAGESTRING,260)VALUE
        call logfromfortran(WARNING_LEVEL,MESSAGESTRING)
      END IF
      IF(J.EQ.6) THEN
        WRITE(MESSAGESTRING,270)VALUE
        call logfromfortran(WARNING_LEVEL,MESSAGESTRING)
      END IF
      IF(J.EQ.7) THEN
        WRITE(MESSAGESTRING,280) VALUE
        call logfromfortran(WARNING_LEVEL,MESSAGESTRING)
      END IF
C
      GO TO 340
C
 330  APICOS(J+3,I)=VALUE
 340  CONTINUE
C 
      IF ( NVAL .GE. NUMVALS ) GO TO 420
      NVAL = NVAL + 1
      GO TO 70
C
 350  CONTINUE
C
C     HAVE NOT FOUND MATCH FOR NAME AND DATE -
C     ADD NEW ENTRY TO CB
C
      IF(NAPICS.LT.10)GO TO 370
C
C     NOT ENOUGH ROOM IN CB
C
      WRITE(MESSAGESTRING,360)
      call logfromfortran(WARNING_LEVEL,MESSAGESTRING)
 360  FORMAT(1H0,10X,'**WARNING** NOT ENOUGH ROOM IN COMMON BLOCK ',
     1 '/FAPICO/'/11X,'TO HOLD A NEW ENTRY OF API-CONT CARRYOVER.')
C
      IF ( NVAL .GE. NUMVALS ) GO TO 420
      NVAL = NVAL + 1
      GO TO 70
C
 370  CONTINUE
C
C     ENOUGH ROOM - ADD NEW ENTRY TO CB
C
      NAPICS=NAPICS+1
      I=NAPICS
      CALL UMEMOV(OPNAME,APICOS(1,I),2)
      APICOS(3,I)=IDATE+0.01
      DO 380 J=4,12
 380  APICOS(J,I)=-999.
      DO 410 J=1,7
      VALUE=VALUES(J)
      IF(VALUE.LT.-9998.) GO TO 410
      IF(J.LT.6.AND.VALUE.GE.0.) GO TO 400
      IF(J.EQ.6.AND.VALUE.GE.-450..AND.VALUE.LE.32.) GO TO 400
      IF(J.EQ.7.AND.VALUE.GE.0.0.AND.VALUE.LE.1.0) GO TO 400
C
C     INVALID RANGE FOR VALUE
C
      WRITE(MESSAGESTRING,250) KWRDS(J)
      call logfromfortran(WARNING_LEVEL,MESSAGESTRING)

      IF (J.LT.6) THEN
        WRITE(MESSAGESTRING,260)VALUE
        call logfromfortran(WARNING_LEVEL,MESSAGESTRING)
      END IF
      IF (J.EQ.6) THEN
        WRITE(MESSAGESTRING,270)VALUE
        call logfromfortran(WARNING_LEVEL,MESSAGESTRING)
      END IF
      IF (J.EQ.7) THEN
        WRITE(MESSAGESTRING,280) VALUE
        call logfromfortran(WARNING_LEVEL,MESSAGESTRING)
      END IF
      GO TO 410
C
 400  APICOS(J+3,I)=VALUE
 410  CONTINUE
      IF ( NVAL .GE. NUMVALS ) GO TO 420
      NVAL = NVAL + 1
C      NVAL = NAVL + 1  --- this line has typo error, fixed as above line by RHC for FogBugz 614 at Nov. 2012
      GO TO 70
C!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 420  CONTINUE 
      WRITE(MESSAGESTRING,430) NAPICS
      call logfromfortran(DEBUG_LEVEL, MESSAGESTRING) 
 430  FORMAT(1HO,10X,'APPLY APICCO MOD - NAPICS = ',I3)
C
      IF (NAPICS.GT.0) THEN
         WRITE(MESSAGESTRING,440)((APICOS(I,J),I=1,12),J=1,NAPICS)
         call logfromfortran(DEBUG_LEVEL,MESSAGESTRING)
 440     FORMAT(11X,'APICOS=',1X,2A4,F8.0,9F8.2)
      END IF
C
      WRITE(MESSAGESTRING,*) '==> LEAVING SUBROUTINE MAPICC'
      call logfromfortran(DEBUG_LEVEL, MESSAGESTRING)
C
      RETURN
      END
