[metadata]
name = nwsrfspy
version = 0.1.0
description = Python tools for NWSRFS modeling with FORTRAN source Code integration
author = Geoffrey Walters PE
author_email = geoffrey.walters@noaa.gov
license = Apache
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/NOAA-NWRFC/nwsrfs-hydro-models

[options]
packages = find:
python_requires = >=3.10
install_requires =
    numpy
    pandas
    scipy
include_package_data = True

[options.package_data]
nwsrfspy = 
    *.so