PGM = genStatesRessngl

RESSNGL_DIR = ../../ressngl

OTHERLIB = ${RESSNGL_DIR}/lib/libressngl.a
OTHERINCLUDE = -I${RESSNGL_DIR}/include -I${RESSNGL_DIR}/include/common
BUILD = objs
SUBDIRS = genStatesRessngl

#include ../Makefile4TopgenStates
include ../Makefile4Top
