#!/usr/bin/ksh
usage="USAGE: run.ressngl \n"
#set -o xtrace

rm -f memcheck

for segdef in apap1llh  apap1llh_6z  calb_40yrs  chsp1chs  chsp1chs_mod  darnc \
              gdmv2jks  kitm2pot  potterp1  remv2rap  spkp1hr1  \
	      spkp1hr1_cox2  waln6del;
do
inputDir=$PWD/testData/$segdef

progname=${PWD##*/}
echo $progname
echo "Basin Name: " $segdef
dirname=bin

#CNRFC -8(PST ); ABRFC -6(CDT ); NERFC -5(Z  ); NCRFC -6(Z   )
ARGUMENTS_FILE=$inputDir/arguments.txt

#rm old files produced by model
rm -f $inputDir/output.txt $inputDir/statesO.txt $inputDir/diag.txt

echo
$dirname/$progname $ARGUMENTS_FILE

#echo '==============> ' $segdef >> memcheck
#valgrind --track-origins=yes --tool=memcheck --leak-check=full --show-reachable=yes $dirname/$progname $ARGUMENTS_FILE >> memcheck 2>&1

echo
diff $inputDir/output.txt $inputDir/output.txt.orig
if [[ $? == 0 ]]
then 
   echo " No timeseries diffs found."
fi

if [[ $segdef == "potterp1" ]]
then
   echo " No comparision statesO.txt for FFG model"
   printf "===================== DONE $segdef ==========================\n\n"
   continue
fi

diff $inputDir/statesO.txt $inputDir/statesO.txt.orig
if [[ $? == 0 ]]
then
   echo " No StatesO diffs found."
fi

#set +o xtrace
printf "===================== DONE $segdef ==========================\n\n"
#set -o xtrace
done
