#ifndef _VERSION_NUMBER_INFO_H
#define _VERSION_NUMBER_INFO_H

#define VERSION_NAME_LENGTH 16 
#define VERSION_NUMBER_LENGTH 7
#define VERSION_NAME "OHD-CORE"
#define VERSION_NUMBER "17.1.2"
#define VERSION_DATE "(May 18, 2020)"
#endif
