#!/usr/bin/ksh
usage="USAGE: run.ressngl \n"
#set -o xtrace

rm -f memcheck
for segdef in `ls -1d testData/*`
do
inputDir=$PWD/$segdef

progname=${PWD##*/}
echo $progname
echo "Basin Name: " $segdef
dirname=bin

#CNRFC -8(PST ); ABRFC -6(CDT ); NERFC -5(Z  ); NCRFC -6(Z   )
ARGUMENTS_FILE=$inputDir/arguments.txt

#rm old files produced by model
rm -f $inputDir/output.txt $inputDir/statesO.txt $inputDir/diag.txt

echo
echo '=================> ' $segdef >> memcheck
$dirname/$progname $ARGUMENTS_FILE
#valgrind --track-origins=yes --tool=memcheck --leak-check=full --show-reachable=yes $dirname/$progname $ARGUMENTS_FILE >> memcheck 2>&1
echo
diff $inputDir/output.txt $inputDir/output.txt.orig
if [[ $? == 0 ]]
then
   echo -e "\n No timeseries diffs found."
fi

diff $inputDir/statesO.txt $inputDir/statesO.txt.orig
if [[ $? == 0 ]]
then
   echo -e " No StatesO diffs found.\n"
fi
#set +o xtrace
printf "===================== DONE $segdef ==========================\n\n"
#set -o xtrace
done
