C MEMBER OBSV26
C  (from old member FCOBSV26)
C
      FUNCTION OBSV26(S2,IBUG)
C
C FUNCTION OBSV26 SETS IGO TO 0 IF THE POOL STORAGE (S2) AT THE END OF
C THE TIME INTERVAL IS MISSING AND SETS IGO TO 1 IF THE POOL STORAGE
C (S2) IS NOT MISSING.  OBSV26 IS USED ONLY FOR THE TIME INTERVALS UP TO
C RUN TIME.
C
C THIS FUNCTION WAS ORIGINALLY PROGRAMMED BY
C     WILLIAM E. FOX -- CONSULTING HYDROLOGIST
C     JANUARY, 1983
C
C FUNCTION OBSV26 IS IN
C
C VARIABLES IN THE ARGUMENT LIST ARE DEFINED AS FOLLOWS:
C     S2 -- STORAGE AT THE END OF THE TIME INTERVAL.
C     IBUG -- NO TRACE OR DEBUG (IBUG=0), TRACE ONLY (IBUG=1), TRACE AND
C       DEBUG (IBUG=2).
C
!CP   COMMON/FDBUG/IODBUG,ITRACE,IDBALL,NDEBUG,IDEBUG(20)
      INCLUDE 'flogm'
C
C    ================================= RCS keyword statements ==========
      CHARACTER*68     RCSKW1,RCSKW2
      DATA             RCSKW1,RCSKW2 /                                 '
     .$Source: /fs/hseb/ob72/rfc/ofs/src/fcst_res/RCS/obsv26.f,v $
     . $',                                                             '
     .$Id: obsv26.f,v 1.1 1995/09/17 19:05:52 dws Exp $
     . $' /
C    ===================================================================
C
C
C WRITE TRACE AND DEBUG IF REQUIRED.
C
!CP   IF(IBUG-1) 50,10,20
!CP   10 WRITE(IODBUG,30)
!CP   GO TO 50
!CP   20 WRITE(IODBUG,30)

      IF( FEWSDEBUG.LT.4 ) GO TO 50
      WRITE(MESSAGESTRING, 30)
      call logfromfortran(DEBUG_LEVEL, MESSAGESTRING)
   30 FORMAT(1H0,10X,17H** OBSV26 ENTERED)

!CP   WRITE(IODBUG,40) S2,IBUG
      WRITE(MESSAGESTRING, 40) S2,IBUG
      call logfromfortran(DEBUG_LEVEL, MESSAGESTRING)
   40 FORMAT(1H0,8H S2,IBUG/1X,F12.3,I6)
C
C IGO DIRECTS THE COMPUTATIONS TO THE PROPER LOCATION IN THE OPERATIONAL
C SUBROUTINE.
C
   50 IGO=1
      IF(S2.EQ.-999.0) IGO=0
      OBSV26=IGO

!CP   IF(IBUG-1) 100,80,60
      IF ( FEWSDEBUG.LT.4 ) GO TO 100
!CP   60 WRITE(IODBUG,70) IGO,S2,IBUG
      WRITE(MESSAGESTRING, 70) IGO,S2,IBUG
      call logfromfortran(DEBUG_LEVEL, MESSAGESTRING)
   70 FORMAT(1H0,12H IGO,S2,IBUG/1X,I6,F12.3,I6)

!CP   80 WRITE(IODBUG,90)
      WRITE(MESSAGESTRING, 90)
      call logfromfortran(DEBUG_LEVEL, MESSAGESTRING)
   90 FORMAT(1H0,10X,17H** LEAVING OBSV26)
  100 RETURN
      END
