C MEMBER XADO26
C  (from old member FCXADO26)
C
C DESC OUTPUT ADJUSTED VALUES TO TIME-SERIES IF NEEDED
C----------------------------------------------------------------------
      SUBROUTINE XADO26(W,D,LOCTRM,LOCTRI,LOCTRE,LOCTRS,LRPPOS,LRPVAL)
C--------------------------------------------------------------------
C  SUBROUTINE TO CHECK ON NEED FOR OUTPUTTING ADJUSTED VALUES,
C  CONVERTING VALUES IF NECESSARY AND TRANSFERRING VALUES TO TIME-SERIES
C----------------------------------------------------------------------
C  WRITTEN BY - JOE OSTROWSKI - HRL - NOVEMBER 1983
C--------------------------------------------------------------------
C
      INCLUDE 'common/exg26'
!CP   INCLUDE 'common/fdbug'
      INCLUDE 'common/resv26'
      INCLUDE 'flogm'
C
      DIMENSION W(1),D(1)
C
C    ================================= RCS keyword statements ==========
      CHARACTER*68     RCSKW1,RCSKW2
      DATA             RCSKW1,RCSKW2 /                                 '
     .$Source: /fs/hseb/ob72/rfc/ofs/src/fcst_res/RCS/xado26.f,v $
     . $',                                                             '
     .$Id: xado26.f,v 1.3 2004/05/18 20:04:03 hsu Exp $
     . $' /
C    ===================================================================
C
C
C------------------------------
C  TRACE OUTPUT IF REQUESTED
C
!CP   IF (IBUG.GE.1) WRITE(IODBUG,1600) NTIM24,MINODT
      IF ( FEWSDEBUG.GE.4 ) THEN
         WRITE(MESSAGESTRING, 1600) NTIM24,MINODT 
         call logfromfortran(DEBUG_LEVEL, MESSAGESTRING)
 1600    FORMAT('   *** ENTER XADO26 ***-->NTIM24 & MINODT = ',2I10)
      END IF
C
C     IF (IBUG.LT.2) GO TO 10
!CP   IF (IBUG.GE.0) GO TO 10
      IF ( FEWSDEBUG.LT.4 ) GO TO 10
C
!CP   WRITE(IODBUG,1605) WRAJQI,WRAJQM,WRAJEL,WRAJST
      WRITE(MESSAGESTRING, 1605) WRAJQI,WRAJQM,WRAJEL,WRAJST
      call logfromfortran(DEBUG_LEVEL, MESSAGESTRING)
 1605 FORMAT('   WRAJQI WRAJQM WRAJEL WRAJST'/4(6X,L1))
C
C  WRITE INST. ADJ. DISCHARGES
C
!1650 FORMAT(1X,8F10.0)
!CP   WRITE(IODBUG,1610)
      NPRINT=NUM
      IF ( NPRINT.GT.100 ) NPRINT=100
      
      WRITE(MESSAGESTRING, 1610)
      call logfromfortran(DEBUG_LEVEL, MESSAGESTRING)
 1610 FORMAT(/10X,'** INST. ADJ. DISCHARGES **')

!     WRITE(IODBUG,1650) (W(LOCTRI+I-1),I=1,NUM)
      WRITE(FORMATSTR, *) '%10.0f'
      call logonedimensionarrayfromfortran(DEBUG_LEVEL,NULLLINE,1,8,
     >     FORMATSTR,LOCTRI,LOCTRI+NPRINT-1,1,W)
      
C
C  WRITE MEAN ADJ. DISCHARGES
C
!CP   WRITE(IODBUG,1612)
      WRITE(MESSAGESTRING, 1612)
      call logfromfortran(DEBUG_LEVEL, MESSAGESTRING)
 1612 FORMAT(/10X,'** MEAN ADJ. DISCHARGES **')

!CP   WRITE(IODBUG,1650) (W(LOCTRM+I-1),I=1,NUM)
      WRITE(FORMATSTR, *) '%10.0f'
      call logonedimensionarrayfromfortran(DEBUG_LEVEL,NULLLINE,1,8,
     >     FORMATSTR,LOCTRM,LOCTRM+NPRINT-1,1,W)
      
C
C  WRITE ADJ. POOL ELEVATIONS
C
!CP   WRITE(IODBUG,1614)
      WRITE(MESSAGESTRING, 1614)
      call logfromfortran(DEBUG_LEVEL, MESSAGESTRING)
 1614 FORMAT(/10X,'** ADJ. POOL ELEVATIONS **')

!CP   WRITE(IODBUG,1651) (W(LOCTRE+I-1),I=1,NUM)
!1651 FORMAT(1X,8F10.3)
      WRITE(FORMATSTR, *) '%10.3f'
      call logonedimensionarrayfromfortran(DEBUG_LEVEL,NULLLINE,1,8,
     >     FORMATSTR,LOCTRE,LOCTRE+NPRINT-1,1,W)
      
C
!CP   WRITE(IODBUG,1615)
      WRITE(MESSAGESTRING, 1615)
      call logfromfortran(DEBUG_LEVEL, MESSAGESTRING)
 1615 FORMAT(/10X,'** ADJ. POOL STORAGE **')

!CP   WRITE(IODBUG,1650) (W(LOCTRS+I-1),I=1,NUM)
      WRITE(FORMATSTR, *) '%10.0f'
      call logonedimensionarrayfromfortran(DEBUG_LEVEL,NULLLINE,1,8,
     >     FORMATSTR,LOCTRS,LOCTRS+NPRINT-1,1,W)
      
C
   10 CONTINUE
C
C  IF ADJUSTED MEAN DISCHARGE IS TO BE OUTPUT, CONVERT THE VALUES TO
C  CMSD.
C
      IF (.NOT.WRAJQM) GO TO 600
C
C  SET INTERVAL SCHEDULE FOR WRITING OUTPUT TO TIME-SERIES.
C
      NINT = IDTAJM/MINODT
C
      DO 550 I=1,NUM
      IF (MOD(I,NINT) .NE. 0) GO TO 550
      D(LADJQM+I-1) = W(LOCTRM+I-1)/NTIM24
  550 CONTINUE
C
C  NEXT IS INSTANTANEOUS DISCHARGE
C
  600 CONTINUE
      IF (.NOT.WRAJQI) GO TO 700
C
C  SET TIME INTERVAL SCHEDULE FOR OUTPUTTING TO TIME-SERIES
C
      NINT = IDTAJI/MINODT
C
      DO 650 I=1,NUM
      IF (MOD(I,NINT) .NE. 0) GO TO 650
      D(LADJQI+I-1) = W(LOCTRI+I-1)
  650 CONTINUE
C
C  NEXT IS POOL ELEVATION
C
  700 CONTINUE
      IF (.NOT.WRAJEL) GO TO 800
C
C  SET TIME INTERVAL SCHEDULE FOR OUTPUTTING TO TIME-SERIES
C
      NINT = IDTAJE/MINODT
C
      DO 750 I=1,NUM
      IF (MOD(I,NINT) .NE. 0) GO TO 750
      D(LADJEL+I-1) = W(LOCTRE+I-1)
  750 CONTINUE
C
C  NEXT IS POOL STORAGE
C
  800 CONTINUE
      IF (.NOT.WRAJST) GO TO 900
C
C  SET TIME INTERVAL SCHEDULE FOR OUTPUTTING TO TIME-SERIES
C
      NINT = IDTAJS/MINODT
C
      DO 850 I=1,NUM
      IF (MOD(I,NINT) .NE. 0) GO TO 850
      D(LADJST+I-1) = W(LOCTRS+I-1)/NTIM24
  850 CONTINUE
C
C  CHECK TO SEE IF PEAK VALUES NEED TO BE REPLACED IN INST. DISCHARGE
C  TIME SERIES.
C
  900 CONTINUE
      IF (NUMPKO .LE. 0 .OR. .NOT.WRAJQI) GO TO 9000
      DO 950 I=1,NUMPKO
      IPOS = W(LRPPOS+I-1)
      VAL =  W(LRPVAL+I-1)
      D(LADJQI+IPOS-1) = VAL
  950 CONTINUE
C
C  ALL DONE OUTPUTTING INFO TO TIME-SERIES FOR ADJUSTED RUN.
C
 9000 CONTINUE
!CP   IF (IBUG.GE.1) WRITE(IODBUG,1699) NTIM24,MINODT
      IF ( FEWSDEBUG.GE.4 ) THEN
         WRITE(MESSAGESTRING, 1699) NTIM24,MINODT
         call logfromfortran(DEBUG_LEVEL, MESSAGESTRING)
 1699    FORMAT('    *** EXIT XADO26 ***-->NTIM24 & MINODT = ',2I10)
      END IF  
      RETURN
      END
