C MEMBER XOUT26
C  (from old member FCXOUT26)
C
C DESC OUTPUT TIME-SERIES GENERATED BY 'BACKFLOW' AND 'RAINEVAP' UTILS
C-------------------------------------------------------------------
      SUBROUTINE XOUT26(W,D,LOCOWS)
C------------------------------------------------------------------
C  ROUTINE TO CHECK ON NEED FOR AND PERFORM THE OUTPUT OF 'BACKFLOW'
C  ADJUSTED INFLOWS AND 'RAINEVAP' GENERATED ADD'L FLOWS.
C------------------------------------------------------------------
C  WRITTEN BY - JOE OSTROWSKI - OCTOBER 1983
C------------------------------------------------------------------
C
      INCLUDE 'common/resv26'
      INCLUDE 'common/exg26'
      INCLUDE 'common/xre26'
!CP   INCLUDE 'common/fdbug'
      INCLUDE 'flogm'
C
      DIMENSION W(1),D(1),LOCOWS(1)
C
C    ================================= RCS keyword statements ==========
      CHARACTER*68     RCSKW1,RCSKW2
      DATA             RCSKW1,RCSKW2 /                                 '
     .$Source: /fs/hseb/ob72/rfc/ofs/src/fcst_res/RCS/xout26.f,v $
     . $',                                                             '
     .$Id: xout26.f,v 1.3 2005/02/22 14:03:16 hsu Exp $
     . $' /
C    ===================================================================
C
C
C  TRACE OUTPUT IF REQUIRED
C
!CP   IF (IBUG.GE.1) WRITE(IODBUG,1600)
!CP   1600 FORMAT('   *** ENTER XOUT26 ***')
      IF ( FEWSDEBUG.GE.4 ) THEN
         WRITE(MESSAGESTRING, '(A23)') '   *** ENTER XOUT26 ***'
	 call logfromfortran(DEBUG_LEVEL, MESSAGESTRING)
      END IF
C
C----------------------------------------------------------------
C  FIRST CHECK ON NEED TO OUTPUT 'BACKFLOW' ADJUSTED INFLOWS
C  WILL BE DONE IN XQT26 AFTER XRIN26 ROUTINE -- 3/19/2002   
C
      IF (.NOT.BFSAVQ) GO TO 200
      DO 100 I=1,NUM
      D(LTSBFQ+I-1) = W(LOCOWS(1)+I-1)
  100 CONTINUE
!CP   IF (IBUG.GE.1)  WRITE(IODBUG,1604) (D(LTSBFQ+I-1),I=1,NUM)
      IF ( FEWSDEBUG.GE.4 ) THEN
         NPRINT=NUM
	 IF ( NPRINT.GT.100 ) NPRINT=100

         WRITE(MESSAGESTRING, 1604) 
         call logfromfortran(DEBUG_LEVEL, MESSAGESTRING)
 1604    FORMAT(' INSTANTEOUS BACK ADJUSTED INFLOW:') 
         WRITE(FORMATSTR, *) '%10.1f'
         call logonedimensionarrayfromfortran(DEBUG_LEVEL,NULLLINE,1,8,
     >        FORMATSTR,LTSBFQ,LTSBFQ+NPRINT-M1,1,D)
      END IF
C
C---------------------------------------------------------------
C  CHECK ON NEED TO OUTPUT 'RAINEVAP' GENERATED ADD'L VOLUMES
C
  200 CONTINUE
      IF (.NOT.WRADLQ) GO TO 1000
C
C  CONVERT VALUES FROM TIMD TO CMSD
C
      DO 300 I=1,NUM
      D(LTSADQ+I-1) = W(LPTADL+I-1)/NTIM24
  300 CONTINUE
C
C--------------------------------------------------------------------
C  THAT'S IT!
C
 1000 CONTINUE
!CP   IF (IBUG.GE.1) WRITE(IODBUG,1699)
!CP   1699 FORMAT('    *** EXIT XOUT26 ***')
      IF ( FEWSDEBUG.GE.4 ) THEN
         WRITE(MESSAGESTRING, '(A23)') '    *** EXIT XOUT26 ***'
	 call logfromfortran(DEBUG_LEVEL, MESSAGESTRING)
      END IF
      RETURN
      END
