#!/usr/bin/ksh
usage="USAGE: runall\n"
#set -o xtrace

#rm -f memcheck

for segdef in almn8 bprt2res crvi4 cyfm4 cyfm4_cox giln6hud \
              lrit2res ltkw3 mmdn6grl pnvs1sys sacn6hud \
	      swrn6grl synres synres_cox_change_node towv1uct \
              towv1uct_cox upsoplat wymm1me wymm1me_cox;
do
inputDir=$PWD/testData/$segdef

progname=${PWD##*/}
echo $progname
echo "Basin Name: " $segdef
dirname=bin

#rm old files produced by model
rm -f $inputDir/output.txt $inputDir/statesO.txt $inputDir/diag.txt

ARGUMENTS_FILE=$inputDir/arguments.txt

echo
#echo '========> ' $segdef >> memcheck
$dirname/$progname $ARGUMENTS_FILE > log.txt
#valgrind --track-origins=yes --tool=memcheck --leak-check=full --show-reachable=yes $dirname/$progname $ARGUMENTS_FILE >> memcheck 2>&1
echo
diff $inputDir/output.txt $inputDir/output.txt.orig
if [[ $? == 0 ]]
then
   echo " No timeseries diffs found."
fi

diff $inputDir/statesO.txt $inputDir/statesO.txt.orig
if [[ $? == 0 ]]
then
   echo -e " No StatesO diffs found.\n"
fi
#set +o xtrace
printf "===================== DONE $segdef ==========================\n\n"
#set -o xtrace
done
